name: Check build

on: [push]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Golang dependency
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build Carmen
        working-directory: ./carmen/go/lib
        run: ./build_libcarmen.sh

      - name: Run unit tests
        run: go test -v ./...

      - name: Build
        run: make opera

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: opera
          path: ./build/opera
