name: Check build

on: [push]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure private dependencies
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: git
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Golang dependency
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Static lints
        env:
          GOPRIVATE: github.com/Fantom-foundation
        run: make lint

      - name: Run unit tests
        env:
          GOPRIVATE: github.com/Fantom-foundation
        run: go test ./... --count 0 

      - name: Build
        run: make
